#Default port is 8761
server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging.level.org.springframework.security: DEBUG


#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mtqiushui.resources?rewriteBatchedStatements=true&autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: rsdata-server