
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8899
  tomcat:
    max-threads: 128
    min-spare-threads: 64
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
      enabled: true

